name: Trigger auto deployment for corm-aca-canadaeast

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/corm-aca-canadaeast-AutoDeployTrigger-d932f2fe-4342-4abe-9234-44758146f580.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CORMACACANADAEAST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CORMACACANADAEAST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CORMACACANADAEAST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CORMACACANADAEAST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CORMACACANADAEAST_REGISTRY_PASSWORD }}
          containerAppName: corm-aca-canadaeast
          resourceGroup: aca-bug-bash-canadaeast
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


